// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#include <dt-bindings/clock/qcom,malabar-gcc.h>

#include <linux/soc/qcom/llcc-qcom.h>
#include <soc/qcom/of_common.h>
#include <soc/qcom/socinfo.h>

#include <media/v4l2_vidc_extensions.h>
#include <media/videobuf2-core.h>
#include "msm_vidc_malabar.h"
#include "msm_vidc_inst.h"
#include "msm_vidc_platform.h"
#include "msm_vidc_debug.h"
#include "msm_vidc_internal.h"
#include "msm_vidc_platform_ext.h"
#include "msm_vidc_memory_ext.h"
#include "resources_ext.h"
#include "msm_vidc_ar50lt.h"
#include "hfi_property.h"
#include "hfi_command.h"
#include "venus_hfi.h"

/* version: major[24:31], minor[16:23], revision[0:15] */
#define DRIVER_VERSION          0x04000000
#define DEFAULT_VIDEO_CONCEAL_COLOR_BLACK 0x8000800010
#define MAX_LTR_FRAME_COUNT     2
#define MAX_BASE_LAYER_PRIORITY_ID 63
#define MAX_BITRATE             100000000
#define DEFAULT_BITRATE         20000000
#define MINIMUM_FPS             1
#define MAXIMUM_FPS             120
#define MIN_QP_10BIT_MALABAR   -12
#define MIN_QP_8BIT_MALABAR    0
#define MAX_QP                  51
#define DEFAULT_QP              20
#define MAX_CONSTANT_QUALITY    100
#define MAX_BITRATE_BOOST_MALABAR  15
#define MIN_SLICE_BYTE_SIZE     512
#define MAX_SLICE_BYTE_SIZE  \
	((MAX_BITRATE) >> 3)
#define MAX_SLICE_MB_SIZE         \
	(((1920 + 15) >> 4) * ((1088 + 15) >> 4))

#define ENC     MSM_VIDC_ENCODER
#define DEC     MSM_VIDC_DECODER
#define H264    MSM_VIDC_H264
#define HEVC    MSM_VIDC_HEVC
#define VP9     MSM_VIDC_VP9
#define HEIC    MSM_VIDC_HEIC
#define CODECS_ALL     (H264 | HEVC | VP9 | HEIC)
#define MAXIMUM_OVERRIDE_VP9_FPS 60

static struct codec_info codec_data_malabar[] = {
	{
		.v4l2_codec  = V4L2_PIX_FMT_H264,
		.vidc_codec  = MSM_VIDC_H264,
		.pixfmt_name = "AVC",
	},
	{
		.v4l2_codec  = V4L2_PIX_FMT_HEVC,
		.vidc_codec  = MSM_VIDC_HEVC,
		.pixfmt_name = "HEVC",
	},
	{
		.v4l2_codec  = V4L2_PIX_FMT_VP9,
		.vidc_codec  = MSM_VIDC_VP9,
		.pixfmt_name = "VP9",
	},
	{
		.v4l2_codec  = V4L2_PIX_FMT_VIDC_HEIC,
		.vidc_codec  = MSM_VIDC_HEIC,
		.pixfmt_name = "HEIC",
	},
};

static struct color_format_info color_format_data_malabar[] = {
	{
		.v4l2_color_format = V4L2_PIX_FMT_NV12,
		.vidc_color_format = MSM_VIDC_FMT_NV12,
		.pixfmt_name       = "NV12",
	},
	{
		.v4l2_color_format = V4L2_PIX_FMT_NV21,
		.vidc_color_format = MSM_VIDC_FMT_NV21,
		.pixfmt_name       = "NV21",
	},
	{
		.v4l2_color_format = V4L2_META_FMT_VIDC,
		.vidc_color_format = MSM_VIDC_FMT_META,
		.pixfmt_name       = "META",
	},
};

static struct color_primaries_info color_primaries_data_malabar[] = {
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_DEFAULT,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_UNSPECIFIED,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_DEFAULT,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_RESERVED,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_REC709,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_BT709,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_470_SYSTEM_M,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_BT470_SYSTEM_M,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_470_SYSTEM_BG,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_BT470_SYSTEM_BG,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_SMPTE170M,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_BT601_525,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_SMPTE240M,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_SMPTE_ST240M,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_VIDC_GENERIC_FILM,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_GENERIC_FILM,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_BT2020,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_BT2020,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_DCI_P3,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_SMPTE_RP431_2,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_VIDC_EG431,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_SMPTE_EG431_1,
	},
	{
		.v4l2_color_primaries  = V4L2_COLORSPACE_VIDC_EBU_TECH,
		.vidc_color_primaries  = MSM_VIDC_PRIMARIES_SMPTE_EBU_TECH,
	},
};

static struct transfer_char_info transfer_char_data_malabar[] = {
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_DEFAULT,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_UNSPECIFIED,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_DEFAULT,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_RESERVED,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_709,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT709,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_BT470_SYSTEM_M,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT470_SYSTEM_M,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_BT470_SYSTEM_BG,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT470_SYSTEM_BG,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_BT601_525_OR_625,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT601_525_OR_625,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_SMPTE240M,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_SMPTE_ST240M,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_LINEAR,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_LINEAR,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_XVYCC,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_XVYCC,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_BT1361,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT1361_0,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_SRGB,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_SRGB_SYCC,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_BT2020,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT2020_14,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_SMPTE2084,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_SMPTE_ST2084_PQ,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_ST428,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_SMPTE_ST428_1,
	},
	{
		.v4l2_transfer_char  = V4L2_XFER_FUNC_VIDC_HLG,
		.vidc_transfer_char  = MSM_VIDC_TRANSFER_BT2100_2_HLG,
	},
};

static struct matrix_coeff_info matrix_coeff_data_malabar[] = {
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_DEFAULT,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_UNSPECIFIED,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_DEFAULT,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_RESERVED,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_VIDC_SRGB_OR_SMPTE_ST428,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_SRGB_SMPTE_ST428_1,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_709,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT709,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_XV709,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT709,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_VIDC_FCC47_73_682,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_FCC_TITLE_47,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_XV601,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT470_SYS_BG_OR_BT601_625,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_601,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT601_525_BT1358_525_OR_625,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_SMPTE240M,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_SMPTE_ST240,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_BT2020,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT2020_NON_CONSTANT,
	},
	{
		.v4l2_matrix_coeff  = V4L2_YCBCR_ENC_BT2020_CONST_LUM,
		.vidc_matrix_coeff  = MSM_VIDC_MATRIX_COEFF_BT2020_CONSTANT,
	},
};

/*
 * IRIS2-1P
 * Dec: 1080P@60
 * Enc: 1080P@60
 */

static const struct msm_platform_core_capability core_data_malabar[] = {
	{ENC_CODECS, H264 | HEVC | HEIC},
	{DEC_CODECS, H264 | HEVC | VP9 | HEIC},
	{MAX_SESSION_COUNT, 8},
	{MAX_NUM_720P_SESSIONS, 4},
	{MAX_NUM_1080P_SESSIONS, 2},
	{MAX_NUM_4K_SESSIONS, 0},
	{MAX_NUM_8K_SESSIONS, 0},
	{MAX_SECURE_SESSION_COUNT, 3},
	{MAX_RT_MBPF, 16320}, /* ((1920x1088)/256)*2 */
	{MAX_MBPF, 32640}, /* ((1920x1088)/256)*4 */
	/* Concurrency: 1080p@30 decode + 1080p@30 encode */
	{MAX_MBPS, 489600}, /* ((1088x1920)/256)@60fps */
	{MAX_IMAGE_MBPF, 262144}, /* (8192x8192)/256 */
	{MAX_MBPF_HQ, 8160}, /* ((1920x1088)/256) */
	{MAX_MBPS_HQ, 244800}, /* ((1920x1088)/256)@30fps */
	{MAX_MBPF_B_FRAME, 0},
	{MAX_MBPS_B_FRAME, 0},
	{MAX_MBPS_ALL_INTRA, 489600}, /* ((1920x1088)/256)@60fps */
	{MAX_ENH_LAYER_COUNT, 5},
	{NUM_VPP_PIPE, 1},
	{SW_PC, 1},
	{FW_UNLOAD, 0},
	{HW_RESPONSE_TIMEOUT, HW_RESPONSE_TIMEOUT_VALUE}, /* 1000 ms */
	{SW_PC_DELAY,         SW_PC_DELAY_VALUE        }, /* 1500 ms (>HW_RESPONSE_TIMEOUT)*/
	{FW_UNLOAD_DELAY,     FW_UNLOAD_DELAY_VALUE    }, /* 3000 ms (>SW_PC_DELAY)*/
	{PAGEFAULT_NON_FATAL, 1},
	{PAGETABLE_CACHING, 0},
	{DCVS, 1},
	{DECODE_BATCH, 0},
	{DECODE_BATCH_TIMEOUT, 200},
	{STATS_TIMEOUT_MS, 2000},
	{AV_SYNC_WINDOW_SIZE, 40},
	{NON_FATAL_FAULTS, 1},
	{ENC_AUTO_FRAMERATE, 0},
	{DEVICE_CAPS, V4L2_CAP_VIDEO_M2M_MPLANE | V4L2_CAP_META_CAPTURE | V4L2_CAP_STREAMING},
	{SUPPORTS_REQUESTS, 0},
};

static struct msm_platform_inst_capability instance_cap_data_malabar[] = {
	/* {cap, domain, codec,
	 *      min, max, step_or_mask, value,
	 *      v4l2_id,
	 *      hfi_id,
	 *      flags}
	 */
	{DRV_VERSION, DEC | ENC, CODECS_ALL,
		0, INT_MAX, 1, DRIVER_VERSION,
		V4L2_CID_MPEG_VIDC_DRIVER_VERSION},

	{FRAME_WIDTH, DEC, CODECS_ALL, 96, 1920, 1, 1920},

	{FRAME_WIDTH, ENC, CODECS_ALL, 128, 1920, 1, 1920},

	{FRAME_WIDTH, ENC, HEIC, 128, 8192, 1, 8192},

	{LOSSLESS_FRAME_WIDTH, ENC, CODECS_ALL, 128, 1920, 1, 1920},

	{SECURE_FRAME_WIDTH, DEC, CODECS_ALL, 96, 1920, 1, 1920},

	{SECURE_FRAME_WIDTH, ENC, CODECS_ALL, 128, 1920, 1, 1920},

	{FRAME_HEIGHT, DEC, CODECS_ALL, 96, 1920, 1, 1080},

	{FRAME_HEIGHT, ENC, CODECS_ALL, 128, 1920, 1, 1080},

	{FRAME_HEIGHT, ENC, HEIC, 128, 16384, 1, 16384},

	{LOSSLESS_FRAME_HEIGHT, ENC, CODECS_ALL, 128, 1920, 1, 1080},

	{SECURE_FRAME_HEIGHT, DEC, CODECS_ALL, 96, 1920, 1, 1080},

	{SECURE_FRAME_HEIGHT, ENC, CODECS_ALL, 128, 1920, 1, 1080},

	{PIX_FMTS, ENC | DEC, CODECS_ALL,
		MSM_VIDC_FMT_NV12,
		MSM_VIDC_FMT_NV21,
		MSM_VIDC_FMT_NV12 | MSM_VIDC_FMT_NV21,
		MSM_VIDC_FMT_NV12},

	{MIN_BUFFERS_INPUT, ENC | DEC, CODECS_ALL, 0, 64, 1, 4,
		V4L2_CID_MIN_BUFFERS_FOR_OUTPUT,
		0,
		CAP_FLAG_VOLATILE},

	{MIN_BUFFERS_INPUT, ENC | DEC, HEIC, 0, 64, 1, 1,
		V4L2_CID_MIN_BUFFERS_FOR_OUTPUT,
		0,
		CAP_FLAG_VOLATILE},

	{MIN_BUFFERS_OUTPUT, ENC | DEC, CODECS_ALL,
		0, 64, 1, 4,
		V4L2_CID_MIN_BUFFERS_FOR_CAPTURE,
		HFI_PROP_BUFFER_FW_MIN_OUTPUT_COUNT,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_VOLATILE},

	/* (1920 * 1088) / 256 */
	{MBPF, ENC | DEC, CODECS_ALL, 64, 8160, 1, 8160},

	/* ((8192x8192)/256) */
	{MBPF, ENC | DEC, HEIC, 36, 262144, 1, 262144},

	/* (1920 * 1088) / 256 */
	{LOSSLESS_MBPF, ENC, H264 | HEVC, 36, 8160, 1, 8160},

	/* Batch Mode Decode */
	/* TODO: update with new values based on updated voltage corner */
	{BATCH_MBPF, DEC, H264 | HEVC | VP9, 36, 8162, 1, 8162},

	/* (4096 * 2304) / 256 */
	{BATCH_FPS, DEC, H264 | HEVC | VP9, 1, 121, 1, 121},

	{SECURE_MBPF, ENC | DEC, H264 | HEVC | VP9, 36, 8160, 1, 8160},

	{FRAME_RATE, ENC, CODECS_ALL,
		(MINIMUM_FPS << 16), (MAXIMUM_FPS << 16),
		1, (DEFAULT_FPS << 16),
		0,
		HFI_PROP_FRAME_RATE,
		CAP_FLAG_OUTPUT_PORT},

	{FRAME_RATE, ENC, HEIC,
		(MINIMUM_FPS << 16), (MAXIMUM_FPS << 16),
		1, (MINIMUM_FPS << 16),
		0,
		HFI_PROP_FRAME_RATE,
		CAP_FLAG_OUTPUT_PORT},

	{FRAME_RATE, DEC, H264 | HEVC | VP9 | HEIC,
		(MINIMUM_FPS << 16), (MAXIMUM_FPS << 16),
		1, (DEFAULT_FPS << 16),
		V4L2_CID_MPEG_VIDC_FRAME_RATE,
		0,
		CAP_FLAG_OUTPUT_PORT |
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{FRAME_RATE, DEC, VP9,
		(MINIMUM_FPS << 16), (MAXIMUM_OVERRIDE_VP9_FPS << 16),
		1, (DEFAULT_FPS << 16),
		V4L2_CID_MPEG_VIDC_FRAME_RATE,
		0,
		CAP_FLAG_OUTPUT_PORT |
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{OPERATING_RATE, ENC, CODECS_ALL,
		(MINIMUM_FPS << 16), INT_MAX,
		1, (DEFAULT_FPS << 16)},

	{OPERATING_RATE, DEC, CODECS_ALL,
		(MINIMUM_FPS << 16), INT_MAX,
		1, (DEFAULT_FPS << 16),
		V4L2_CID_MPEG_VIDC_OPERATING_RATE,
		0,
		CAP_FLAG_OUTPUT_PORT |
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{INPUT_RATE, ENC | DEC, CODECS_ALL,
		(MINIMUM_FPS << 16), INT_MAX,
		1, (DEFAULT_FPS << 16)},

	{TIMESTAMP_RATE, ENC | DEC, CODECS_ALL,
		(MINIMUM_FPS << 16), INT_MAX,
		1, (DEFAULT_FPS << 16)},

	{SCALE_FACTOR, ENC, H264 | HEVC, 1, 8, 1, 8},

	{MB_CYCLES_VSP, ENC, H264 | HEVC | VP9 | HEIC, 0, 0, 0, 0},

	{MB_CYCLES_VSP, DEC, H264 | HEVC | VP9 | HEIC, 0, 0, 0, 0},

	{MB_CYCLES_VPP, ENC, CODECS_ALL, 675, 675, 1, 675},

	{MB_CYCLES_VPP, DEC, CODECS_ALL, 440, 440, 1, 440},

	{MB_CYCLES_LP, ENC, CODECS_ALL, 320, 320, 1, 320},

	{MB_CYCLES_LP, DEC, CODECS_ALL, 440, 440, 1, 440},

	{MB_CYCLES_FW, ENC | DEC, CODECS_ALL, 733003, 733003, 1, 733003},

	{MB_CYCLES_FW_VPP, ENC | DEC, CODECS_ALL, 225975, 225975, 1, 225975},

	{CLIENT_ID, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		INVALID_CLIENT_ID, INT_MAX, 1, INVALID_CLIENT_ID,
		V4L2_CID_MPEG_VIDC_CLIENT_ID},

	{SECURE_MODE, ENC | DEC, H264 | HEVC | VP9,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_SECURE,
		HFI_PROP_SECURE,
		CAP_FLAG_NONE},

	{TS_REORDER, DEC, H264 | HEVC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_TS_REORDER},

	{HFLIP, ENC, CODECS_ALL,
		0, 1, 1, 0,
		V4L2_CID_HFLIP,
		0,
		CAP_FLAG_OUTPUT_PORT |
			CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{VFLIP, ENC, CODECS_ALL,
		0, 1, 1, 0,
		V4L2_CID_VFLIP,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{ROTATION, ENC, CODECS_ALL,
		0, 270, 90, 0,
		V4L2_CID_ROTATE,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{SUPER_FRAME, ENC, H264 | HEVC,
		0, 32, 1, 0,
		V4L2_CID_MPEG_VIDC_SUPERFRAME, 0,
		CAP_FLAG_DYNAMIC_ALLOWED},

	{HEADER_MODE, ENC, H264 | HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEADER_MODE_SEPARATE,
		V4L2_MPEG_VIDEO_HEADER_MODE_JOINED_WITH_1ST_FRAME,
		BIT(V4L2_MPEG_VIDEO_HEADER_MODE_SEPARATE) |
		BIT(V4L2_MPEG_VIDEO_HEADER_MODE_JOINED_WITH_1ST_FRAME),
		V4L2_MPEG_VIDEO_HEADER_MODE_SEPARATE,
		V4L2_CID_MPEG_VIDEO_HEADER_MODE,
		HFI_PROP_SEQ_HEADER_MODE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{PREPEND_SPSPPS_TO_IDR, ENC, H264 | HEVC | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_PREPEND_SPSPPS_TO_IDR},

	{VUI_TIMING_INFO, ENC, H264 | HEVC | HEIC,
		V4L2_MPEG_MSM_VIDC_DISABLE,
		V4L2_MPEG_MSM_VIDC_ENABLE,
		1, V4L2_MPEG_MSM_VIDC_DISABLE,
		V4L2_CID_MPEG_VIDC_VUI_TIMING_INFO,
		HFI_PROP_DISABLE_VUI_TIMING_INFO,
		CAP_FLAG_OUTPUT_PORT},

	{WITHOUT_STARTCODE, ENC, H264 | HEVC | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_HEVC_WITHOUT_STARTCODE,
		HFI_PROP_NAL_LENGTH_FIELD,
		CAP_FLAG_OUTPUT_PORT},

	{NAL_LENGTH_FIELD, ENC, H264 | HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEVC_SIZE_0,
		V4L2_MPEG_VIDEO_HEVC_SIZE_4,
		BIT(V4L2_MPEG_VIDEO_HEVC_SIZE_0) |
		BIT(V4L2_MPEG_VIDEO_HEVC_SIZE_4),
		V4L2_MPEG_VIDEO_HEVC_SIZE_0,
		V4L2_CID_MPEG_VIDEO_HEVC_SIZE_OF_LENGTH_FIELD,
		HFI_PROP_NAL_LENGTH_FIELD,
		CAP_FLAG_MENU | CAP_FLAG_OUTPUT_PORT},

	/* TODO: Firmware introduced enumeration type for this
	 * with and without seq header.
	 */
	{REQUEST_I_FRAME, ENC, H264 | HEVC,
		0, 0, 0, 0,
		V4L2_CID_MPEG_VIDEO_FORCE_KEY_FRAME,
		HFI_PROP_REQUEST_SYNC_FRAME,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	/* Enc: Keeping CABAC and CAVLC as same bitrate.
	 * Dec: there's no use of Bitrate cap
	 */
	{BIT_RATE, ENC, H264 | HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_BITRATE,
		HFI_PROP_TOTAL_BITRATE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{BITRATE_MODE, ENC, H264,
		V4L2_MPEG_VIDEO_BITRATE_MODE_VBR,
		V4L2_MPEG_VIDEO_BITRATE_MODE_CBR,
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_VBR) |
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_CBR),
		V4L2_MPEG_VIDEO_BITRATE_MODE_VBR,
		V4L2_CID_MPEG_VIDEO_BITRATE_MODE,
		HFI_PROP_RATE_CONTROL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{BITRATE_MODE, ENC, HEVC,
		V4L2_MPEG_VIDEO_BITRATE_MODE_VBR,
		V4L2_MPEG_VIDEO_BITRATE_MODE_CQ,
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_VBR) |
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_CBR) |
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_CQ),
		V4L2_MPEG_VIDEO_BITRATE_MODE_VBR,
		V4L2_CID_MPEG_VIDEO_BITRATE_MODE,
		HFI_PROP_RATE_CONTROL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{BITRATE_MODE, ENC, HEIC,
		V4L2_MPEG_VIDEO_BITRATE_MODE_CQ,
		V4L2_MPEG_VIDEO_BITRATE_MODE_CQ,
		BIT(V4L2_MPEG_VIDEO_BITRATE_MODE_CQ),
		V4L2_MPEG_VIDEO_BITRATE_MODE_CQ,
		V4L2_CID_MPEG_VIDEO_BITRATE_MODE,
		HFI_PROP_RATE_CONTROL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{CABAC_MAX_BITRATE, ENC, H264 | HEVC, 0,
		MAX_BITRATE, 1, MAX_BITRATE},

	{CAVLC_MAX_BITRATE, ENC, H264, 0,
		MAX_BITRATE, 1, MAX_BITRATE},

	{ALLINTRA_MAX_BITRATE, ENC, H264 | HEVC, 0,
		MAX_BITRATE, 1, MAX_BITRATE},

	{LOWLATENCY_MAX_BITRATE, ENC, H264 | HEVC, 0,
		MAX_BITRATE, 1, MAX_BITRATE},

	{NUM_COMV, DEC, H264 | HEVC | VP9 | HEIC,
		0, INT_MAX, 1, 0},

	{LOSSLESS, ENC, HEVC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_HEVC_LOSSLESS_CU},

	{FRAME_SKIP_MODE, ENC, H264 | HEVC | HEIC,
		V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_DISABLED,
		V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_BUF_LIMIT,
		BIT(V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_DISABLED) |
		BIT(V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_LEVEL_LIMIT) |
		BIT(V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_BUF_LIMIT),
		V4L2_MPEG_VIDEO_FRAME_SKIP_MODE_DISABLED,
		V4L2_CID_MPEG_VIDEO_FRAME_SKIP_MODE,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{FRAME_RC_ENABLE, ENC, H264 | HEVC | HEIC,
		0, 1, 1, 1,
		V4L2_CID_MPEG_VIDEO_FRAME_RC_ENABLE},

	{CONSTANT_QUALITY, ENC, HEVC,
		1, MAX_CONSTANT_QUALITY, 1, 90,
		V4L2_CID_MPEG_VIDEO_CONSTANT_QUALITY,
		HFI_PROP_CONSTANT_QUALITY,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{CONSTANT_QUALITY, ENC, HEIC,
		1, MAX_CONSTANT_QUALITY, 1, 100,
		V4L2_CID_MPEG_VIDEO_CONSTANT_QUALITY,
		HFI_PROP_CONSTANT_QUALITY,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{GOP_SIZE, ENC, H264 | HEVC,
		0, INT_MAX, 1, 2 * DEFAULT_FPS - 1,
		V4L2_CID_MPEG_VIDEO_GOP_SIZE,
		HFI_PROP_MAX_GOP_FRAMES,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{GOP_SIZE, ENC, HEIC,
		0, INT_MAX, 1, 0 /* all intra */,
		V4L2_CID_MPEG_VIDEO_GOP_SIZE,
		HFI_PROP_MAX_GOP_FRAMES,
		CAP_FLAG_OUTPUT_PORT |
			CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{OPEN_GOP, ENC, HEVC,
		0, 0, 0, 0,
		V4L2_CID_MPEG_VIDC_OPEN_GOP_ENABLE,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{GOP_CLOSURE, ENC, H264 | HEVC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_GOP_CLOSURE,
		0},

	{B_FRAME, ENC, H264 | HEVC,
		0, 0, 1, 0,
		V4L2_CID_MPEG_VIDEO_B_FRAMES,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{B_FRAME, ENC, HEIC,
		0, 0, 0, 0,
		V4L2_CID_MPEG_VIDEO_B_FRAMES,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{BLUR_TYPES, ENC, H264 | HEVC,
		0, 0, 0,0,
		V4L2_CID_MPEG_VIDC_BLUR_TYPES,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{BLUR_RESOLUTION, ENC, H264 | HEVC,
		0, 0, 0, 0,
		V4L2_CID_MPEG_VIDC_BLUR_RESOLUTION,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
		CAP_FLAG_DYNAMIC_ALLOWED},

	{CSC, ENC, H264 | HEVC | HEIC,
		0, 0, 1, 0,
		V4L2_CID_MPEG_VIDC_CSC,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{CSC_CUSTOM_MATRIX, ENC, H264 | HEVC | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_CSC_CUSTOM_MATRIX,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{LOWLATENCY_MODE, ENC, H264 | HEVC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_LOWLATENCY_REQUEST,
		0,
		CAP_FLAG_NONE},

	{LOWLATENCY_MODE, DEC, H264 | HEVC | VP9,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_LOWLATENCY_REQUEST,
		HFI_PROP_SEQ_CHANGE_AT_SYNC_FRAME,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{LTR_COUNT, ENC, H264 | HEVC,
		0, MAX_LTR_FRAME_COUNT, 1, 0,
		V4L2_CID_MPEG_VIDEO_LTR_COUNT,
		HFI_PROP_LTR_COUNT,
		CAP_FLAG_OUTPUT_PORT},

	{USE_LTR, ENC, H264 | HEVC,
		0,
		((1 << MAX_LTR_FRAME_COUNT) - 1),
		0, 0,
		V4L2_CID_MPEG_VIDEO_USE_LTR_FRAMES,
		HFI_PROP_LTR_USE,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{MARK_LTR, ENC, H264 | HEVC,
		INVALID_DEFAULT_MARK_OR_USE_LTR,
		(MAX_LTR_FRAME_COUNT - 1),
		1, INVALID_DEFAULT_MARK_OR_USE_LTR,
		V4L2_CID_MPEG_VIDEO_FRAME_LTR_INDEX,
		HFI_PROP_LTR_MARK,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{BASELAYER_PRIORITY, ENC, H264,
		0, MAX_BASE_LAYER_PRIORITY_ID, 1, 0,
		V4L2_CID_MPEG_VIDEO_BASELAYER_PRIORITY_ID,
		HFI_PROP_BASELAYER_PRIORITYID,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{IR_TYPE, ENC, H264 | HEVC,
		V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE_RANDOM,
		V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE_RANDOM,
		BIT(V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE_RANDOM) |
		BIT(V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE_RANDOM),
		V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE_RANDOM,
		V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD_TYPE,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{IR_PERIOD, ENC, H264 | HEVC,
		0, INT_MAX, 1, 0,
		V4L2_CID_MPEG_VIDEO_INTRA_REFRESH_PERIOD,
		0,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_OUTPUT_PORT |
		CAP_FLAG_DYNAMIC_ALLOWED},

	{AU_DELIMITER, ENC, H264 | HEVC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_AU_DELIMITER,
		HFI_PROP_AUD,
		CAP_FLAG_OUTPUT_PORT},

	{TIME_DELTA_BASED_RC, ENC, H264 | HEVC,
		0, 1, 1, 1,
		V4L2_CID_MPEG_VIDC_TIME_DELTA_BASED_RC,
		HFI_PROP_TIME_DELTA_BASED_RATE_CONTROL,
		CAP_FLAG_OUTPUT_PORT},

	{TIME_DELTA_BASED_RC, ENC, HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_TIME_DELTA_BASED_RC,
		HFI_PROP_TIME_DELTA_BASED_RATE_CONTROL,
		CAP_FLAG_OUTPUT_PORT},

	{CONTENT_ADAPTIVE_CODING, ENC, H264 | HEVC,
		0, 0, 1, 0,
		V4L2_CID_MPEG_VIDC_CONTENT_ADAPTIVE_CODING,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{BITRATE_BOOST, ENC, H264 | HEVC,
		0, MAX_BITRATE_BOOST_MALABAR, 25, MAX_BITRATE_BOOST_MALABAR,
		V4L2_CID_MPEG_VIDC_QUALITY_BITRATE_BOOST,
		HFI_PROP_BITRATE_BOOST,
		CAP_FLAG_OUTPUT_PORT},

	{MIN_QUALITY, ENC, H264 | HEVC,
		0, MAX_SUPPORTED_MIN_QUALITY, 70, MAX_SUPPORTED_MIN_QUALITY,
		0,
		HFI_PROP_MAINTAIN_MIN_QUALITY,
		CAP_FLAG_OUTPUT_PORT},

	{VBV_DELAY, ENC, H264 | HEVC,
		200, 300, 100, 300,
		V4L2_CID_MPEG_VIDEO_VBV_DELAY,
		HFI_PROP_VBV_DELAY,
		CAP_FLAG_OUTPUT_PORT},

	{PEAK_BITRATE, ENC, H264 | HEVC,
		/* default peak bitrate is 10% larger than avg bitrate */
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_BITRATE_PEAK,
		HFI_PROP_TOTAL_PEAK_BITRATE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{MIN_FRAME_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MIN_QP_8BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_H264_MIN_QP,
		HFI_PROP_MIN_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT},

	{MIN_FRAME_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MIN_QP_10BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_HEVC_MIN_QP,
		HFI_PROP_MIN_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT},

	{I_FRAME_MIN_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MIN_QP_8BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_H264_I_FRAME_MIN_QP},

	{I_FRAME_MIN_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MIN_QP_10BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_HEVC_I_FRAME_MIN_QP},

	{P_FRAME_MIN_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MIN_QP_8BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_H264_P_FRAME_MIN_QP},

	{P_FRAME_MIN_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MIN_QP_10BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_HEVC_P_FRAME_MIN_QP},

	{B_FRAME_MIN_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MIN_QP_8BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_H264_B_FRAME_MIN_QP},

	{B_FRAME_MIN_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MIN_QP_10BIT_MALABAR,
		V4L2_CID_MPEG_VIDEO_HEVC_B_FRAME_MIN_QP},

	{MAX_FRAME_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_H264_MAX_QP,
		HFI_PROP_MAX_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT},

	{MAX_FRAME_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_MAX_QP,
		HFI_PROP_MAX_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT},

	{I_FRAME_MAX_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_H264_I_FRAME_MAX_QP},

	{I_FRAME_MAX_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_I_FRAME_MAX_QP},

	{P_FRAME_MAX_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_H264_P_FRAME_MAX_QP},

	{P_FRAME_MAX_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_P_FRAME_MAX_QP},

	{B_FRAME_MAX_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_H264_B_FRAME_MAX_QP},

	{B_FRAME_MAX_QP, ENC, HEVC | HEIC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, MAX_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_B_FRAME_MAX_QP},

	{I_FRAME_QP, ENC, HEVC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_I_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{I_FRAME_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_H264_I_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{P_FRAME_QP, ENC, HEVC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_P_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{P_FRAME_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_H264_P_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{B_FRAME_QP, ENC, HEVC,
		MIN_QP_10BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_HEVC_B_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{B_FRAME_QP, ENC, H264,
		MIN_QP_8BIT_MALABAR, MAX_QP, 1, DEFAULT_QP,
		V4L2_CID_MPEG_VIDEO_H264_B_FRAME_QP,
		HFI_PROP_QP_PACKED,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{LAYER_TYPE, ENC, HEVC,
		V4L2_MPEG_VIDEO_HEVC_HIERARCHICAL_CODING_P,
		V4L2_MPEG_VIDEO_HEVC_HIERARCHICAL_CODING_P,
		BIT(V4L2_MPEG_VIDEO_HEVC_HIERARCHICAL_CODING_P),
		V4L2_MPEG_VIDEO_HEVC_HIERARCHICAL_CODING_P,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_TYPE,
		HFI_PROP_LAYER_ENCODING_TYPE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LAYER_TYPE, ENC, H264,
		V4L2_MPEG_VIDEO_H264_HIERARCHICAL_CODING_P,
		V4L2_MPEG_VIDEO_H264_HIERARCHICAL_CODING_P,
		BIT(V4L2_MPEG_VIDEO_H264_HIERARCHICAL_CODING_P),
		V4L2_MPEG_VIDEO_H264_HIERARCHICAL_CODING_P,
		V4L2_CID_MPEG_VIDEO_H264_HIERARCHICAL_CODING_TYPE,
		HFI_PROP_LAYER_ENCODING_TYPE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LAYER_ENABLE, ENC, H264,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_H264_HIERARCHICAL_CODING,
		HFI_PROP_LAYER_ENCODING_TYPE,
		CAP_FLAG_OUTPUT_PORT},

	{LAYER_ENABLE, ENC, HEVC,
		0, 1, 1, 0,
		0,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{ENH_LAYER_COUNT, ENC, HEVC,
		0, 5, 1, 0,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_LAYER,
		HFI_PROP_LAYER_COUNT,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{ENH_LAYER_COUNT, ENC, H264,
		0, 5, 1, 0,
		V4L2_CID_MPEG_VIDEO_H264_HIERARCHICAL_CODING_LAYER,
		HFI_PROP_LAYER_COUNT,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L0_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L0_BR,
		HFI_PROP_BITRATE_LAYER1,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L0_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L0_BR,
		HFI_PROP_BITRATE_LAYER1,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L1_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L1_BR,
		HFI_PROP_BITRATE_LAYER2,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L1_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L1_BR,
		HFI_PROP_BITRATE_LAYER2,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L2_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L2_BR,
		HFI_PROP_BITRATE_LAYER3,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L2_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L2_BR,
		HFI_PROP_BITRATE_LAYER3,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L3_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L3_BR,
		HFI_PROP_BITRATE_LAYER4,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},
	{L3_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L3_BR,
		HFI_PROP_BITRATE_LAYER4,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L4_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L4_BR,
		HFI_PROP_BITRATE_LAYER5,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L4_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L4_BR,
		HFI_PROP_BITRATE_LAYER5,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L5_BR, ENC, H264,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_H264_HIER_CODING_L5_BR,
		HFI_PROP_BITRATE_LAYER6,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{L5_BR, ENC, HEVC,
		1, MAX_BITRATE, 1, DEFAULT_BITRATE,
		V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_L5_BR,
		HFI_PROP_BITRATE_LAYER6,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_INPUT_PORT |
			CAP_FLAG_DYNAMIC_ALLOWED},

	{ENTROPY_MODE, ENC, H264,
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CAVLC,
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC,
		BIT(V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CAVLC) |
		BIT(V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC),
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC,
		V4L2_CID_MPEG_VIDEO_H264_ENTROPY_MODE,
		HFI_PROP_CABAC_SESSION,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{ENTROPY_MODE, DEC, H264 | HEVC | VP9,
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CAVLC,
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC,
		BIT(V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CAVLC) |
		BIT(V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC),
		V4L2_MPEG_VIDEO_H264_ENTROPY_MODE_CABAC,
		0,
		HFI_PROP_CABAC_SESSION},

	{PROFILE, ENC | DEC, H264,
		V4L2_MPEG_VIDEO_H264_PROFILE_BASELINE,
		V4L2_MPEG_VIDEO_H264_PROFILE_CONSTRAINED_HIGH,
		BIT(V4L2_MPEG_VIDEO_H264_PROFILE_BASELINE) |
		BIT(V4L2_MPEG_VIDEO_H264_PROFILE_CONSTRAINED_HIGH) |
		BIT(V4L2_MPEG_VIDEO_H264_PROFILE_CONSTRAINED_BASELINE) |
		BIT(V4L2_MPEG_VIDEO_H264_PROFILE_MAIN) |
		BIT(V4L2_MPEG_VIDEO_H264_PROFILE_HIGH),
		V4L2_MPEG_VIDEO_H264_PROFILE_HIGH,
		V4L2_CID_MPEG_VIDEO_H264_PROFILE,
		HFI_PROP_PROFILE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{PROFILE, ENC | DEC, HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN,
		V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_STILL_PICTURE,
		BIT(V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN) |
		BIT(V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN_STILL_PICTURE),
		V4L2_MPEG_VIDEO_HEVC_PROFILE_MAIN,
		V4L2_CID_MPEG_VIDEO_HEVC_PROFILE,
		HFI_PROP_PROFILE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{PROFILE, DEC, VP9,
		V4L2_MPEG_VIDEO_VP9_PROFILE_0,
		V4L2_MPEG_VIDEO_VP9_PROFILE_0,
		BIT(V4L2_MPEG_VIDEO_VP9_PROFILE_0),
		V4L2_MPEG_VIDEO_VP9_PROFILE_0,
		V4L2_CID_MPEG_VIDEO_VP9_PROFILE,
		HFI_PROP_PROFILE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LEVEL, ENC, H264,
		V4L2_MPEG_VIDEO_H264_LEVEL_1_0,
		V4L2_MPEG_VIDEO_H264_LEVEL_4_2,
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1B) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_3) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_2),
		V4L2_MPEG_VIDEO_H264_LEVEL_4_2,
		V4L2_CID_MPEG_VIDEO_H264_LEVEL,
		HFI_PROP_LEVEL,
		CAP_FLAG_VOLATILE | CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LEVEL, ENC, HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEVC_LEVEL_1,
		V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1,
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_2) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_2_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_3) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_3_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_4) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1),
		V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1,
		V4L2_CID_MPEG_VIDEO_HEVC_LEVEL,
		HFI_PROP_LEVEL,
		CAP_FLAG_VOLATILE | CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LEVEL, DEC, H264,
		V4L2_MPEG_VIDEO_H264_LEVEL_1_0,
		V4L2_MPEG_VIDEO_H264_LEVEL_4_2,
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1B) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_1_3) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_2_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_3_2) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_0) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_1) |
		BIT(V4L2_MPEG_VIDEO_H264_LEVEL_4_2),
		V4L2_MPEG_VIDEO_H264_LEVEL_4_2,
		V4L2_CID_MPEG_VIDEO_H264_LEVEL,
		HFI_PROP_LEVEL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LEVEL, DEC, HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEVC_LEVEL_1,
		V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1,
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_2) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_2_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_3) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_3_1) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_4) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1),
		V4L2_MPEG_VIDEO_HEVC_LEVEL_4_1,
		V4L2_CID_MPEG_VIDEO_HEVC_LEVEL,
		HFI_PROP_LEVEL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LEVEL, DEC, VP9,
		V4L2_MPEG_VIDEO_VP9_LEVEL_1_0,
		V4L2_MPEG_VIDEO_VP9_LEVEL_4_1,
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_1_0) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_1_1) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_2_0) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_2_1) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_3_0) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_3_1) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_4_0) |
		BIT(V4L2_MPEG_VIDEO_VP9_LEVEL_4_1),
		V4L2_MPEG_VIDEO_VP9_LEVEL_4_1,
		V4L2_CID_MPEG_VIDEO_VP9_LEVEL,
		HFI_PROP_LEVEL,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{HEVC_TIER, ENC | DEC, HEVC,
		V4L2_MPEG_VIDEO_HEVC_TIER_MAIN,
		V4L2_MPEG_VIDEO_HEVC_TIER_HIGH,
		BIT(V4L2_MPEG_VIDEO_HEVC_TIER_MAIN) |
		BIT(V4L2_MPEG_VIDEO_HEVC_TIER_HIGH),
		V4L2_MPEG_VIDEO_HEVC_TIER_HIGH,
		V4L2_CID_MPEG_VIDEO_HEVC_TIER,
		HFI_PROP_TIER,
		CAP_FLAG_VOLATILE | CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{HEVC_TIER, ENC | DEC, HEIC,
		V4L2_MPEG_VIDEO_HEVC_TIER_MAIN,
		V4L2_MPEG_VIDEO_HEVC_TIER_MAIN,
		BIT(V4L2_MPEG_VIDEO_HEVC_TIER_MAIN),
		V4L2_MPEG_VIDEO_HEVC_TIER_MAIN,
		V4L2_CID_MPEG_VIDEO_HEVC_TIER,
		HFI_PROP_TIER,
		CAP_FLAG_VOLATILE | CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LF_MODE, ENC, H264,
		V4L2_MPEG_VIDEO_H264_LOOP_FILTER_MODE_ENABLED,
		DB_H264_DISABLE_SLICE_BOUNDARY,
		BIT(V4L2_MPEG_VIDEO_H264_LOOP_FILTER_MODE_ENABLED) |
		BIT(V4L2_MPEG_VIDEO_H264_LOOP_FILTER_MODE_DISABLED) |
		BIT(DB_H264_DISABLE_SLICE_BOUNDARY),
		V4L2_MPEG_VIDEO_H264_LOOP_FILTER_MODE_ENABLED,
		V4L2_CID_MPEG_VIDEO_H264_LOOP_FILTER_MODE,
		HFI_PROP_DEBLOCKING_MODE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LF_MODE, ENC, HEVC | HEIC,
		V4L2_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE_DISABLED,
		DB_HEVC_DISABLE_SLICE_BOUNDARY,
		BIT(V4L2_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE_DISABLED) |
		BIT(V4L2_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE_ENABLED) |
		BIT(DB_HEVC_DISABLE_SLICE_BOUNDARY),
		V4L2_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE_ENABLED,
		V4L2_CID_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE,
		HFI_PROP_DEBLOCKING_MODE,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{LF_ALPHA, ENC, H264,
		-6, 6, 1, 0,
		V4L2_CID_MPEG_VIDEO_H264_LOOP_FILTER_ALPHA},

	{LF_ALPHA, ENC, HEVC | HEIC,
		-6, 6, 1, 0,
		V4L2_CID_MPEG_VIDEO_HEVC_LF_TC_OFFSET_DIV2},

	{LF_BETA, ENC, H264,
		-6, 6, 1, 0,
		V4L2_CID_MPEG_VIDEO_H264_LOOP_FILTER_BETA},

	{LF_BETA, ENC, HEVC | HEIC,
		-6, 6, 1, 0,
		V4L2_CID_MPEG_VIDEO_HEVC_LF_BETA_OFFSET_DIV2},

	{SLICE_MODE, ENC, H264 | HEVC | HEIC,
		V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_SINGLE,
		V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_MAX_BYTES,
		BIT(V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_SINGLE) |
		BIT(V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_MAX_MB) |
		BIT(V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_MAX_BYTES),
		V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_SINGLE,
		V4L2_CID_MPEG_VIDEO_MULTI_SLICE_MODE,
		0,
		CAP_FLAG_OUTPUT_PORT | CAP_FLAG_MENU},

	{SLICE_MAX_BYTES, ENC, H264 | HEVC | HEIC,
		MIN_SLICE_BYTE_SIZE, MAX_SLICE_BYTE_SIZE,
		1, MIN_SLICE_BYTE_SIZE,
		V4L2_CID_MPEG_VIDEO_MULTI_SLICE_MAX_BYTES,
		HFI_PROP_MULTI_SLICE_BYTES_COUNT,
		CAP_FLAG_OUTPUT_PORT},

	{SLICE_MAX_MB, ENC, H264 | HEVC | HEIC,
		1, MAX_SLICE_MB_SIZE, 1, 1,
		V4L2_CID_MPEG_VIDEO_MULTI_SLICE_MAX_MB,
		HFI_PROP_MULTI_SLICE_MB_COUNT,
		CAP_FLAG_OUTPUT_PORT},

	{MB_RC, ENC, H264 | HEVC,
		0, 0, 0, 0,
		V4L2_CID_MPEG_VIDEO_MB_RC_ENABLE,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{TRANSFORM_8X8, ENC, H264,
		0, 1, 1, 1,
		V4L2_CID_MPEG_VIDEO_H264_8X8_TRANSFORM,
		HFI_PROP_8X8_TRANSFORM,
		CAP_FLAG_OUTPUT_PORT},

	{CHROMA_QP_INDEX_OFFSET, ENC, HEVC | H264,
		MIN_CHROMA_QP_OFFSET, MAX_CHROMA_QP_OFFSET,
		1, MAX_CHROMA_QP_OFFSET,
		V4L2_CID_MPEG_VIDEO_H264_CHROMA_QP_INDEX_OFFSET,
		HFI_PROP_CHROMA_QP_OFFSET,
		CAP_FLAG_OUTPUT_PORT},

	{DISPLAY_DELAY_ENABLE, DEC, H264 | HEVC | VP9,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_DEC_DISPLAY_DELAY_ENABLE,
		HFI_PROP_DECODE_ORDER_OUTPUT,
		CAP_FLAG_INPUT_PORT},

	{DISPLAY_DELAY, DEC, H264 | HEVC | VP9,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDEO_DEC_DISPLAY_DELAY,
		HFI_PROP_DECODE_ORDER_OUTPUT,
		CAP_FLAG_INPUT_PORT},

	{OUTPUT_ORDER, DEC, H264 | HEVC | VP9,
		0, 1, 1, 0,
		0,
		HFI_PROP_DECODE_ORDER_OUTPUT,
		CAP_FLAG_INPUT_PORT},

	{INPUT_BUF_HOST_MAX_COUNT, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		DEFAULT_MAX_HOST_BUF_COUNT, DEFAULT_MAX_HOST_BURST_BUF_COUNT,
		1, DEFAULT_MAX_HOST_BUF_COUNT,
		0,
		HFI_PROP_BUFFER_HOST_MAX_COUNT,
		CAP_FLAG_INPUT_PORT},

	{OUTPUT_BUF_HOST_MAX_COUNT, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		DEFAULT_MAX_HOST_BUF_COUNT, DEFAULT_MAX_HOST_BURST_BUF_COUNT,
		1, DEFAULT_MAX_HOST_BUF_COUNT,
		0,
		HFI_PROP_BUFFER_HOST_MAX_COUNT,
		CAP_FLAG_OUTPUT_PORT},

	{CONCEAL_COLOR_8BIT, DEC, CODECS_ALL, 0x0, 0xff3fcff, 1,
		DEFAULT_VIDEO_CONCEAL_COLOR_BLACK,
		V4L2_CID_MPEG_VIDEO_MUTE_YUV,
		HFI_PROP_CONCEAL_COLOR_8BIT,
		CAP_FLAG_OUTPUT_PORT},

	{STAGE, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_STAGE_1,
		MSM_VIDC_STAGE_2, 1,
		MSM_VIDC_STAGE_2,
		0,
		HFI_PROP_STAGE},

	{PIPE, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_PIPE_NONE,
		MSM_VIDC_PIPE_NONE, 0,
		MSM_VIDC_PIPE_NONE,
		0,
		HFI_PROP_PIPE},

	{POC, DEC, H264,
		0, 2, 1, 1,
		0,
		HFI_PROP_PIC_ORDER_CNT_TYPE,
		CAP_FLAG_VOLATILE},

	/*
	 * value of MAX_NUM_REORDER_FRAMES is 32 packed as mentioned below
	 * (max_num_reorder_count << 16) | max_dec_frame_buffering_count
	 */
	{MAX_NUM_REORDER_FRAMES, DEC, H264 | HEVC,
		0, INT_MAX, 1, 0,
		V4L2_CID_MPEG_VIDC_MAX_NUM_REORDER_FRAMES,
		HFI_PROP_MAX_NUM_REORDER_FRAMES,
		CAP_FLAG_VOLATILE},

	{QUALITY_MODE, ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_MAX_QUALITY_MODE,
		MSM_VIDC_MAX_QUALITY_MODE, 1,
		MSM_VIDC_MAX_QUALITY_MODE},

	{CODED_FRAMES, DEC, H264 | HEVC | HEIC,
		CODED_FRAMES_PROGRESSIVE, CODED_FRAMES_INTERLACE,
		1, CODED_FRAMES_PROGRESSIVE,
		V4L2_CID_MPEG_VIDC_INTERLACE,
		HFI_PROP_CODED_FRAMES,
		CAP_FLAG_VOLATILE},

	{BIT_DEPTH, DEC | ENC, CODECS_ALL, BIT_DEPTH_8, BIT_DEPTH_8, 1, BIT_DEPTH_8,
		0,
		HFI_PROP_LUMA_CHROMA_BIT_DEPTH},

	{CODEC_CONFIG, DEC, H264 | HEVC | HEIC, 0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_CODEC_CONFIG, 0,
		CAP_FLAG_DYNAMIC_ALLOWED},

	{BITSTREAM_SIZE_OVERWRITE, DEC, H264 | HEVC | VP9 | HEIC, 0, INT_MAX, 1, 0,
		V4L2_CID_MPEG_VIDC_MIN_BITSTREAM_SIZE_OVERWRITE},

	{THUMBNAIL_MODE, DEC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_THUMBNAIL_MODE,
		HFI_PROP_THUMBNAIL_MODE,
		CAP_FLAG_INPUT_PORT},

	{DEFAULT_HEADER, DEC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 0,
		0,
		HFI_PROP_DEC_DEFAULT_HEADER},

	{RAP_FRAME, DEC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 1,
		0,
		HFI_PROP_DEC_START_FROM_RAP_FRAME,
		CAP_FLAG_INPUT_PORT},

	{SEQ_CHANGE_AT_SYNC_FRAME, DEC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 1,
		0,
		HFI_PROP_SEQ_CHANGE_AT_SYNC_FRAME,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},

	{PRIORITY, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		0, 2, 1, 1,
		V4L2_CID_MPEG_VIDC_PRIORITY,
		HFI_PROP_SESSION_PRIORITY,
		CAP_FLAG_DYNAMIC_ALLOWED},

	{FIRMWARE_PRIORITY_OFFSET, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		1, 1, 1, 1},

	{CRITICAL_PRIORITY, ENC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_CRITICAL_PRIORITY},

	{ENC_IP_CR, ENC, H264 | HEVC | VP9 | HEIC,
		0, S32_MAX, 1, 0,
		V4L2_CID_MPEG_VIDC_COMPRESSION_RATIO,
		0, CAP_FLAG_DYNAMIC_ALLOWED},

	{INPUT_EXTRA_METADATA_OFFSET, DEC, H264 | HEVC | VP9 | HEIC,
		0, INT_MAX, 1, 0,
		V4L2_CID_MPEG_VIDC_INPUT_EXTRA_METADATA_OFFSET,
		0, CAP_FLAG_DYNAMIC_ALLOWED},

	{LAST_FLAG_EVENT_ENABLE, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		0, 1, 1, 0,
		V4L2_CID_MPEG_VIDC_LAST_FLAG_EVENT_ENABLE},

	{ALL_INTRA, ENC, H264 | HEVC,
		0, 1, 1, 0,
		0,
		0,
		CAP_FLAG_OUTPUT_PORT},

	{META_LTR_MARK_USE, ENC, H264 | HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_LTR_MARK_USE_DETAILS,
		HFI_PROP_LTR_MARK_USE_DETAILS,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SEQ_HDR_NAL, ENC, H264 | HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SEQ_HEADER_NAL,
		HFI_PROP_METADATA_SEQ_HEADER_NAL,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_DPB_MISR, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_DPB_LUMA_CHROMA_MISR,
		HFI_PROP_DPB_LUMA_CHROMA_MISR,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_OPB_MISR, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_OPB_LUMA_CHROMA_MISR,
		HFI_PROP_OPB_LUMA_CHROMA_MISR,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_INTERLACE, DEC, H264,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_INTERLACE,
		HFI_PROP_INTERLACE_INFO,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_TIMESTAMP, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_TIMESTAMP,
		HFI_PROP_TIMESTAMP,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_CONCEALED_MB_CNT, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_CONCEALED_MB_COUNT,
		HFI_PROP_CONEALED_MB_COUNT,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_HIST_INFO, DEC, HEVC | VP9,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_DISABLE | MSM_VIDC_META_RX_OUTPUT,
		1, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_HISTOGRAM_INFO,
		0,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_HIST_INFO, ENC, HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_DISABLE | MSM_VIDC_META_RX_OUTPUT,
		1, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_HISTOGRAM_INFO,
		0,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_HDR10_MAX_RGB_INFO, ENC, HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_DISABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_HDR10_MAX_RGB_INFO,
		0,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_TRANSCODING_STAT_INFO, DEC, HEVC | H264,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_DISABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_TRANSCODE_STAT_INFO,
		0,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_TRANSCODING_STAT_INFO, ENC, HEVC | H264,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_DISABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_TRANSCODE_STAT_INFO,
		0,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_PICTURE_TYPE, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_TX_INPUT |
		MSM_VIDC_META_RX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_PICTURE_TYPE,
		HFI_PROP_PICTURE_TYPE,
		CAP_FLAG_BITMASK | CAP_FLAG_META | CAP_FLAG_DYNAMIC_ALLOWED},

	{META_SEI_MASTERING_DISP, ENC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE |
		MSM_VIDC_META_DYN_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SEI_MDCV,
		HFI_PROP_SEI_MASTERING_DISPLAY_COLOUR,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SEI_MASTERING_DISP, DEC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_INPUT |
			MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SEI_MDCV,
		HFI_PROP_SEI_MASTERING_DISPLAY_COLOUR,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SEI_CLL, ENC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE |
		MSM_VIDC_META_DYN_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SEI_CLL,
		HFI_PROP_SEI_CONTENT_LIGHT_LEVEL,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SEI_CLL, DEC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_INPUT |
			MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SEI_CLL,
		HFI_PROP_SEI_CONTENT_LIGHT_LEVEL,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_HDR10PLUS, ENC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE |
		MSM_VIDC_META_DYN_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_HDR10PLUS,
		HFI_PROP_SEI_HDR10PLUS_USERDATA,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_HDR10PLUS, DEC, HEVC | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_INPUT |
			MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_HDR10PLUS,
		HFI_PROP_SEI_HDR10PLUS_USERDATA,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_EVA_STATS, ENC, H264 | HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE |
		MSM_VIDC_META_DYN_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_EVA_STATS,
		HFI_PROP_EVA_SV_STAT_INFO,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_BUF_TAG, ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_TX_INPUT |
			MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_BUFFER_TAG,
		HFI_PROP_BUFFER_TAG,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	/*
	 * when fence enabled, client needs output buffer_tag
	 * in input metadata buffer done.
	 */
	{META_BUF_TAG, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_TX_INPUT |
			MSM_VIDC_META_TX_OUTPUT | MSM_VIDC_META_RX_INPUT |
			MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_BUFFER_TAG,
		HFI_PROP_BUFFER_TAG,
		CAP_FLAG_BITMASK | CAP_FLAG_META | CAP_FLAG_DYNAMIC_ALLOWED},

	{META_DPB_TAG_LIST, DEC, H264 | HEVC | HEIC | VP9,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_DPB_TAG_LIST,
		HFI_PROP_DPB_TAG_LIST,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SUBFRAME_OUTPUT, ENC, HEIC | H264 | HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SUBFRAME_OUTPUT,
		HFI_PROP_SUBFRAME_OUTPUT,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SUBFRAME_OUTPUT, DEC, H264 | HEVC | HEIC | VP9,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SUBFRAME_OUTPUT,
		HFI_PROP_SUBFRAME_OUTPUT,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_ENC_QP_METADATA, ENC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_ENC_QP_METADATA,
		HFI_PROP_ENC_QP_METADATA,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_ROI_INFO, ENC, H264 | HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_ROI_INFO,
		HFI_PROP_ROI_INFO,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_SALIENCY_INFO, ENC, H264 | HEVC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_TX_INPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_SALIENCY_INFO,
		0,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_BITMASK | CAP_FLAG_META},

	{META_DEC_QP_METADATA, DEC, H264 | HEVC | VP9 | HEIC,
		MSM_VIDC_META_DISABLE,
		MSM_VIDC_META_ENABLE | MSM_VIDC_META_RX_OUTPUT,
		0, MSM_VIDC_META_DISABLE,
		V4L2_CID_MPEG_VIDC_METADATA_QP,
		HFI_PROP_DEC_QP_METADATA,
		CAP_FLAG_BITMASK | CAP_FLAG_META},

	{GRID_ENABLE, ENC, HEIC,
		0, 1, 1, 1,
		0,
		HFI_PROP_HEIC_GRID_ENABLE,
		CAP_FLAG_OUTPUT_PORT},

	{GRID_SIZE, ENC, HEIC,
		HEIC_GRID_WIDTH, HEIC_GRID_WIDTH * 2,
		HEIC_GRID_WIDTH, HEIC_GRID_WIDTH,
		V4L2_CID_MPEG_VIDC_GRID_WIDTH},

	{COMPLEXITY, ENC, H264 | HEVC,
		0, 100,
		1, DEFAULT_COMPLEXITY,
		V4L2_CID_MPEG_VIDC_COMPLEXITY},

	{SIGNAL_COLOR_INFO, ENC, H264 | HEVC | HEIC,
		0, INT_MAX, 1, 0,
		V4L2_CID_MPEG_VIDC_SIGNAL_COLOR_INFO,
		HFI_PROP_SIGNAL_COLOR_INFO,
		CAP_FLAG_INPUT_PORT | CAP_FLAG_DYNAMIC_ALLOWED},
};

static struct msm_platform_inst_cap_dependency instance_cap_dependency_data_malabar[] = {
	/* {cap, domain, codec,
	 *      children,
	 *      adjust, set}
	 */

	{PIX_FMTS, ENC, H264,
		{IR_PERIOD, CSC, BIT_DEPTH}},

	{PIX_FMTS, ENC, HEVC,
		{PROFILE, MIN_FRAME_QP, MAX_FRAME_QP, I_FRAME_QP, P_FRAME_QP,
			B_FRAME_QP, MIN_QUALITY, BLUR_TYPES, IR_PERIOD,
			LTR_COUNT, CSC, BIT_DEPTH}},

	{PIX_FMTS, ENC, HEIC,
		{PROFILE, CSC, BIT_DEPTH}},

	{PIX_FMTS, DEC, HEVC | HEIC,
		{PROFILE}},

	{BIT_DEPTH, ENC, CODECS_ALL,
		{0},
		msm_vidc_adjust_bitdepth},

	{FRAME_RATE, ENC, CODECS_ALL,
		{LEVEL},
		NULL,
		msm_vidc_set_q16},

	{FRAME_RATE, DEC, CODECS_ALL,
		{0},
		msm_vidc_adjust_dec_frame_rate},

	{OPERATING_RATE, DEC, CODECS_ALL,
		{0},
		msm_vidc_adjust_dec_operating_rate},

	{SECURE_MODE, ENC | DEC, H264 | HEVC | VP9,
		{0},
		NULL,
		msm_vidc_set_u32},

	{HFLIP, ENC, CODECS_ALL,
		{0},
		NULL,
		msm_vidc_set_flip},

	{VFLIP, ENC, CODECS_ALL,
		{0},
		NULL,
		msm_vidc_set_flip},

	{ROTATION, ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_rotation},

	{SUPER_FRAME, ENC, H264 | HEVC,
		{INPUT_BUF_HOST_MAX_COUNT, OUTPUT_BUF_HOST_MAX_COUNT},
		NULL,
		NULL},

	{HEADER_MODE, ENC, H264 | HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_header_mode},

	{WITHOUT_STARTCODE, ENC, H264 | HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_nal_length},

	{REQUEST_I_FRAME, ENC, H264 | HEVC,
		{0},
		NULL,
		msm_vidc_set_req_sync_frame},

	{BIT_RATE, ENC, H264,
		{PEAK_BITRATE, BITRATE_BOOST, L0_BR, LEVEL},
		msm_vidc_adjust_bitrate,
		msm_vidc_set_bitrate},

	{BIT_RATE, ENC, HEVC,
		{PEAK_BITRATE, BITRATE_BOOST, L0_BR, LEVEL},
		msm_vidc_adjust_bitrate,
		msm_vidc_set_bitrate},

	{BITRATE_MODE, ENC, H264,
		{LTR_COUNT, IR_PERIOD, TIME_DELTA_BASED_RC, I_FRAME_QP,
			P_FRAME_QP, B_FRAME_QP, ENH_LAYER_COUNT, BIT_RATE,
			META_ROI_INFO, MIN_QUALITY, BITRATE_BOOST, VBV_DELAY,
			PEAK_BITRATE, SLICE_MODE, CONTENT_ADAPTIVE_CODING,
			BLUR_TYPES, LOWLATENCY_MODE, META_EVA_STATS,
			META_TRANSCODING_STAT_INFO},
		msm_vidc_adjust_bitrate_mode,
		msm_vidc_set_u32_enum},

	{BITRATE_MODE, ENC, HEVC,
		{LTR_COUNT, IR_PERIOD, TIME_DELTA_BASED_RC, I_FRAME_QP,
			P_FRAME_QP, B_FRAME_QP, CONSTANT_QUALITY, ENH_LAYER_COUNT,
			BIT_RATE, META_ROI_INFO, MIN_QUALITY, BITRATE_BOOST, VBV_DELAY,
			PEAK_BITRATE, SLICE_MODE, CONTENT_ADAPTIVE_CODING,
			BLUR_TYPES, LOWLATENCY_MODE, META_EVA_STATS,
			META_TRANSCODING_STAT_INFO, OPEN_GOP},
		msm_vidc_adjust_bitrate_mode,
		msm_vidc_set_u32_enum},

	{BITRATE_MODE, ENC, HEIC,
		{TIME_DELTA_BASED_RC, CONSTANT_QUALITY},
		msm_vidc_adjust_bitrate_mode,
		msm_vidc_set_u32_enum},

	{CONSTANT_QUALITY, ENC, HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_constant_quality},

	{GOP_SIZE, ENC, H264 | HEVC | HEIC,
		{ALL_INTRA},
		msm_vidc_adjust_gop_size,
		msm_vidc_set_gop_size},

	{GOP_SIZE, ENC, HEIC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{OPEN_GOP, ENC, HEVC,
		{GOP_SIZE},
		msm_vidc_adjust_open_gop,
		msm_vidc_set_u32},

	{B_FRAME, ENC, H264 | HEVC,
		{ALL_INTRA},
		msm_vidc_adjust_b_frame,
		msm_vidc_set_u32},

	{B_FRAME, ENC, HEIC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{BLUR_TYPES, ENC, H264 | HEVC,
		{BLUR_RESOLUTION},
		msm_vidc_adjust_blur_type,
		msm_vidc_set_u32_enum},

	{BLUR_RESOLUTION, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_blur_resolution,
		msm_vidc_set_blur_resolution},

	{CSC, ENC, H264 | HEVC | HEIC,
		{CSC_CUSTOM_MATRIX},
		msm_vidc_adjust_csc,
		msm_vidc_set_u32},

	{CSC_CUSTOM_MATRIX, ENC, H264 | HEVC | HEIC,
		{0},
		msm_vidc_adjust_csc_custom_matrix,
		msm_vidc_set_csc_custom_matrix},

	{LOWLATENCY_MODE, ENC, H264 | HEVC,
		{STAGE, BIT_RATE},
		msm_vidc_adjust_enc_lowlatency_mode,
		NULL},

	{LOWLATENCY_MODE, DEC, H264 | HEVC,
		{STAGE},
		NULL,
		NULL},

	{LOWLATENCY_MODE, DEC, VP9,
		{STAGE},
		NULL,
		NULL},

	{LTR_COUNT, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_ltr_count,
		msm_vidc_set_u32},

	{USE_LTR, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_use_ltr,
		msm_vidc_set_use_and_mark_ltr},

	{MARK_LTR, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_mark_ltr,
		msm_vidc_set_use_and_mark_ltr},

	{IR_PERIOD, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_ir_period,
		msm_vidc_set_ir_period},

	{AU_DELIMITER, ENC, H264 | HEVC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{BASELAYER_PRIORITY, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_u32},

	{TIME_DELTA_BASED_RC, ENC, CODECS_ALL,
		{0},
		msm_vidc_adjust_delta_based_rc,
		msm_vidc_set_u32},

	{CONTENT_ADAPTIVE_CODING, ENC, H264 | HEVC,
		{REQUEST_PREPROCESS},
		msm_vidc_adjust_brs,
		msm_vidc_set_vbr_related_properties},

	{REQUEST_PREPROCESS, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_preprocess,
		msm_vidc_set_preprocess},

	{BITRATE_BOOST, ENC, H264 | HEVC,
		{LEVEL},
		msm_vidc_adjust_bitrate_boost,
		msm_vidc_set_vbr_related_properties},

	{MIN_QUALITY, ENC, H264 | HEVC,
		{BLUR_TYPES},
		msm_vidc_adjust_min_quality,
		msm_vidc_set_u32},

	{VBV_DELAY, ENC, H264 | HEVC,
		{0},
		NULL,
		msm_vidc_set_cbr_related_properties},

	{PEAK_BITRATE, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_peak_bitrate,
		msm_vidc_set_cbr_related_properties},

	{MIN_FRAME_QP, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_min_qp},

	{MIN_FRAME_QP, ENC, HEVC,
		{0},
		msm_vidc_adjust_hevc_min_qp,
		msm_vidc_set_min_qp},

	{MAX_FRAME_QP, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_max_qp},

	{MAX_FRAME_QP, ENC, HEVC,
		{0},
		msm_vidc_adjust_hevc_max_qp,
		msm_vidc_set_max_qp},

	{I_FRAME_QP, ENC, HEVC,
		{0},
		msm_vidc_adjust_hevc_i_frame_qp,
		msm_vidc_set_frame_qp},

	{I_FRAME_QP, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_frame_qp},

	{P_FRAME_QP, ENC, HEVC,
		{0},
		msm_vidc_adjust_hevc_p_frame_qp,
		msm_vidc_set_frame_qp},

	{P_FRAME_QP, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_frame_qp},

	{B_FRAME_QP, ENC, HEVC,
		{0},
		msm_vidc_adjust_hevc_b_frame_qp,
		msm_vidc_set_frame_qp},

	{B_FRAME_QP, ENC, H264,
		{0},
		NULL,
		msm_vidc_set_frame_qp},

	{LAYER_TYPE, ENC, H264,
		{CONTENT_ADAPTIVE_CODING, LTR_COUNT, LEVEL}},

	{LAYER_TYPE, ENC, HEVC,
		{CONTENT_ADAPTIVE_CODING, LTR_COUNT, OPEN_GOP}},

	{LAYER_ENABLE, ENC, H264 | HEVC,
		{CONTENT_ADAPTIVE_CODING, LEVEL}},

	{ENH_LAYER_COUNT, ENC, H264,
		{GOP_SIZE, B_FRAME, BIT_RATE, MIN_QUALITY, SLICE_MODE, LTR_COUNT, LEVEL},
		msm_vidc_adjust_layer_count,
		msm_vidc_set_layer_count_and_type},

	{ENH_LAYER_COUNT, ENC, HEVC,
		{GOP_SIZE, B_FRAME, BIT_RATE, MIN_QUALITY, SLICE_MODE, LTR_COUNT, OPEN_GOP},
		msm_vidc_adjust_layer_count,
		msm_vidc_set_layer_count_and_type},

	{L0_BR, ENC, H264 | HEVC,
		{L1_BR},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{L1_BR, ENC, H264 | HEVC,
		{L2_BR},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{L2_BR, ENC, H264 | HEVC,
		{L3_BR},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{L3_BR, ENC, H264 | HEVC,
		{L4_BR},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{L4_BR, ENC, H264 | HEVC,
		{L5_BR},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{L5_BR, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_layer_bitrate,
		msm_vidc_set_layer_bitrate},

	{ENTROPY_MODE, ENC, H264,
		{BIT_RATE},
		msm_vidc_adjust_entropy_mode,
		msm_vidc_set_u32},

	{PROFILE, ENC, H264,
		{ENTROPY_MODE, TRANSFORM_8X8, CHROMA_QP_INDEX_OFFSET},
		NULL,
		msm_vidc_set_u32_enum},

	{PROFILE, DEC, H264,
		{ENTROPY_MODE},
		NULL,
		msm_vidc_set_u32_enum},

	{PROFILE, ENC, HEIC,
		{META_SEI_MASTERING_DISP, META_SEI_CLL, META_HDR10PLUS},
		msm_vidc_adjust_profile,
		msm_vidc_set_u32_enum},

	{PROFILE, ENC, HEVC,
		{META_SEI_MASTERING_DISP, META_SEI_CLL, META_HDR10PLUS,
		META_HIST_INFO, META_HDR10_MAX_RGB_INFO},
		msm_vidc_adjust_profile,
		msm_vidc_set_u32_enum},

	{PROFILE, DEC, HEVC | HEIC,
		{0},
		msm_vidc_adjust_profile,
		msm_vidc_set_u32_enum},

	{PROFILE, DEC, VP9,
		{0},
		NULL,
		msm_vidc_set_u32_enum},

	{LEVEL, DEC, CODECS_ALL,
		{0},
		NULL,
		msm_vidc_set_u32_enum},

	{LEVEL, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_level_tier,
		msm_vidc_set_level},

	{LEVEL, ENC, HEIC,
		{0},
		NULL,
		msm_vidc_set_level},

	{HEVC_TIER, ENC | DEC, HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_u32_enum},

	{LF_MODE, ENC, HEVC | HEIC | H264,
		{0},
		NULL,
		msm_vidc_set_deblock_mode},

	{SLICE_MODE, ENC, H264 | HEVC,
		{STAGE},
		msm_vidc_adjust_slice_count,
		msm_vidc_set_slice_count},

	{SLICE_MODE, ENC, HEIC,
		{0},
		msm_vidc_adjust_slice_count,
		msm_vidc_set_slice_count},

	{TRANSFORM_8X8, ENC, H264,
		{0},
		msm_vidc_adjust_transform_8x8,
		msm_vidc_set_u32},

	{CHROMA_QP_INDEX_OFFSET, ENC, HEVC | H264,
		{0},
		msm_vidc_adjust_chroma_qp_index_offset,
		msm_vidc_set_chroma_qp_index_offset},

	{DISPLAY_DELAY_ENABLE, DEC, H264 | HEVC | VP9,
		{OUTPUT_ORDER},
		NULL,
		NULL},

	{DISPLAY_DELAY, DEC, H264 | HEVC | VP9,
		{OUTPUT_ORDER},
		NULL,
		NULL},

	{OUTPUT_ORDER, DEC, H264 | HEVC,
		{},
		msm_vidc_adjust_output_order,
		msm_vidc_set_u32},

	{OUTPUT_ORDER, DEC, VP9,
		{0},
		msm_vidc_adjust_output_order,
		msm_vidc_set_u32},

	{INPUT_BUF_HOST_MAX_COUNT, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		msm_vidc_adjust_input_buf_host_max_count,
		msm_vidc_set_u32},

	{INPUT_BUF_HOST_MAX_COUNT, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_input_buf_host_max_count,
		msm_vidc_set_u32},

	{OUTPUT_BUF_HOST_MAX_COUNT, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		msm_vidc_adjust_output_buf_host_max_count,
		msm_vidc_set_u32},

	{OUTPUT_BUF_HOST_MAX_COUNT, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_output_buf_host_max_count,
		msm_vidc_set_u32},

	{CONCEAL_COLOR_8BIT, DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_conceal_color},

	{CONCEAL_COLOR_10BIT, DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_conceal_color},

	{STAGE, ENC | DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_stage},

	{STAGE, ENC, H264 | HEVC,
		{0},
		NULL,
		msm_vidc_set_stage},

	{STAGE, DEC, H264 | HEVC | VP9,
		{0},
		NULL,
		msm_vidc_set_stage},

	{PIPE, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_pipe},

	{THUMBNAIL_MODE, DEC, H264 | HEVC | VP9,
		{OUTPUT_ORDER},
		NULL,
		msm_vidc_set_u32},

	{THUMBNAIL_MODE, DEC, HEIC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{RAP_FRAME, DEC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{PRIORITY, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		msm_vidc_adjust_session_priority,
		msm_vidc_set_session_priority},

	{FIRMWARE_PRIORITY_OFFSET, DEC | ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		NULL},

	{CRITICAL_PRIORITY, ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		NULL},

	{RESERVE_DURATION, ENC, H264 | HEVC | VP9 | HEIC,
		{0},
		NULL,
		msm_vidc_set_reserve_duration},

	{ALL_INTRA, ENC, H264 | HEVC,
		{LTR_COUNT, IR_PERIOD, SLICE_MODE, BIT_RATE},
		msm_vidc_adjust_all_intra,
		NULL},

	{META_EVA_STATS, ENC, H264 | HEVC,
		{0},
		msm_vidc_adjust_eva_stats,
		NULL},

	{META_ROI_INFO, ENC, H264 | HEVC,
		{MIN_QUALITY, IR_PERIOD, BLUR_TYPES},
		msm_vidc_adjust_roi_info_iris4,
		NULL},

	{GRID_ENABLE, ENC, HEIC,
		{0},
		NULL,
		msm_vidc_set_u32},

	{VUI_TIMING_INFO, ENC, H264 | HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_vui_timing_info},

	{SIGNAL_COLOR_INFO, ENC, H264 | HEVC | HEIC,
		{0},
		NULL,
		msm_vidc_set_signal_color_info},

	{META_SEI_MASTERING_DISP, ENC, HEVC | HEIC,
		{0},
		msm_vidc_adjust_sei_mastering_disp,
		NULL},

	{META_SEI_CLL, ENC, HEVC | HEIC,
		{0},
		msm_vidc_adjust_sei_cll,
		NULL},

	{META_HDR10PLUS, ENC, HEVC | HEIC,
		{0},
		msm_vidc_adjust_hdr10plus,
		NULL},

	{META_TRANSCODING_STAT_INFO, ENC, HEVC | H264,
		{0},
		msm_vidc_adjust_transcoding_stats,
		NULL},

	{META_HIST_INFO, ENC, HEVC,
		{0},
		msm_vidc_adjust_histogram_info,
		NULL},

	{META_HDR10_MAX_RGB_INFO, ENC, HEVC,
		{0},
		msm_vidc_adjust_hdr10_max_rgb_info,
		NULL},
};

static struct msm_vidc_format_capability format_data_malabar = {
	.codec_info = codec_data_malabar,
	.codec_info_size = ARRAY_SIZE(codec_data_malabar),
	.color_format_info = color_format_data_malabar,
	.color_format_info_size = ARRAY_SIZE(color_format_data_malabar),
	.color_prim_info = color_primaries_data_malabar,
	.color_prim_info_size = ARRAY_SIZE(color_primaries_data_malabar),
	.transfer_char_info = transfer_char_data_malabar,
	.transfer_char_info_size = ARRAY_SIZE(transfer_char_data_malabar),
	.matrix_coeff_info = matrix_coeff_data_malabar,
	.matrix_coeff_info_size = ARRAY_SIZE(matrix_coeff_data_malabar),
};

/* name, min_kbps, max_kbps */
static const struct bw_table malabar_bw_table[] = {
	{ "venus-cnoc",  1000, 1000    },
	{ "venus-ddr",   1000, 6500000 },
};

/* name, hw_trigger */
static const struct regulator_table malabar_regulator_table[] = {
	{ "venus",       0 },
	{ "venus-core0", 1 },
};

/* name, clock id, scaling */
static const struct clk_table malabar_clk_table[] = {
	{ "core_clk",        GCC_VIDEO_VENUS_CTL_CLK,         0},
	{ "bus_clk",         GCC_VENUS_CTL_AXI_CLK,           0},
	{ "core0_clk",       GCC_VIDEO_VCODEC0_SYS_CLK,       0},
	{ "core0_bus_clk",   GCC_VCODEC0_AXI_CLK,             0},
	{ "throttle_clk",    GCC_VIDEO_THROTTLE_CORE_CLK,     0},
	{ "video_clk_src",   GCC_VIDEO_VENUS_CLK_SRC,         1,
	 (u64[]) {420000000, 384000000, 365000000, 240000000, 133330000}, 5},
};

/* name, start, size, secure, dma_coherant, region, dma_mask */
const struct context_bank_table malabar_context_bank_table[] = {
	{"qcom,vidc,cb-ns",             0x25800000, 0xba800000, 0, 1,
		MSM_VIDC_NON_SECURE |
		MSM_VIDC_NON_SECURE_PIXEL |
		MSM_VIDC_NON_SECURE_BITSTREAM, 0 },
	{"qcom,vidc,cb-sec-non-pxl",    0x01000000, 0x24800000, 1, 0,
		MSM_VIDC_SECURE_NONPIXEL,      0 },
	{"qcom,vidc,cb-sec-bitstream",  0x00500000, 0xdfb00000, 1, 0,
		MSM_VIDC_SECURE_BITSTREAM,     0 },
	{"qcom,vidc,cb-sec-pxl",        0x00500000, 0xdfb00000, 1, 0,
		MSM_VIDC_SECURE_PIXEL,         0 },
};

/* register, value, mask */
static const struct reg_preset_table malabar_reg_preset_table[] = {
	{ 0xB0080, 0x0, 0x03},
};

/* decoder properties */
static const u32 malabar_vdec_psc_avc[] = {
	HFI_PROP_BITSTREAM_RESOLUTION,
	HFI_PROP_CROP_OFFSETS,
	HFI_PROP_CODED_FRAMES,
	HFI_PROP_BUFFER_FW_MIN_OUTPUT_COUNT,
	HFI_PROP_PIC_ORDER_CNT_TYPE,
	HFI_PROP_PROFILE,
	HFI_PROP_LEVEL,
	HFI_PROP_SIGNAL_COLOR_INFO,
};

static const u32 malabar_vdec_psc_hevc[] = {
	HFI_PROP_BITSTREAM_RESOLUTION,
	HFI_PROP_CROP_OFFSETS,
	HFI_PROP_LUMA_CHROMA_BIT_DEPTH,
	HFI_PROP_BUFFER_FW_MIN_OUTPUT_COUNT,
	HFI_PROP_PROFILE,
	HFI_PROP_LEVEL,
	HFI_PROP_TIER,
	HFI_PROP_SIGNAL_COLOR_INFO,
};

static const u32 malabar_vdec_psc_vp9[] = {
	HFI_PROP_BITSTREAM_RESOLUTION,
	HFI_PROP_CROP_OFFSETS,
	HFI_PROP_LUMA_CHROMA_BIT_DEPTH,
	HFI_PROP_BUFFER_FW_MIN_OUTPUT_COUNT,
	HFI_PROP_PROFILE,
	HFI_PROP_LEVEL,
};

static const u32 malabar_vdec_input_properties_avc[] = {
	HFI_PROP_NO_OUTPUT,
	HFI_PROP_SUBFRAME_INPUT,
};

static const u32 malabar_vdec_input_properties_hevc[] = {
	HFI_PROP_NO_OUTPUT,
	HFI_PROP_SUBFRAME_INPUT,
};

static const u32 malabar_vdec_input_properties_vp9[] = {
	HFI_PROP_NO_OUTPUT,
	HFI_PROP_SUBFRAME_INPUT,
};

static const u32 malabar_vdec_output_properties_avc[] = {
	HFI_PROP_WORST_COMPRESSION_RATIO,
	HFI_PROP_WORST_COMPLEXITY_FACTOR,
	HFI_PROP_PICTURE_TYPE,
	HFI_PROP_CABAC_SESSION,
	HFI_PROP_DPB_LIST,
};

static const u32 malabar_vdec_output_properties_hevc[] = {
	HFI_PROP_WORST_COMPRESSION_RATIO,
	HFI_PROP_WORST_COMPLEXITY_FACTOR,
	HFI_PROP_PICTURE_TYPE,
	HFI_PROP_DPB_LIST,
};

static const u32 malabar_vdec_output_properties_vp9[] = {
	HFI_PROP_WORST_COMPRESSION_RATIO,
	HFI_PROP_WORST_COMPLEXITY_FACTOR,
	HFI_PROP_PICTURE_TYPE,
	HFI_PROP_DPB_LIST,
};

static const u32 malabar_msm_vidc_ssr_type[] = {
	HFI_SSR_TYPE_SW_ERR_FATAL,
};

static const struct msm_vidc_platform_data malabar_data = {
	/* resources dependent on other module */
	.bw_tbl = malabar_bw_table,
	.bw_tbl_size = ARRAY_SIZE(malabar_bw_table),
	.regulator_tbl = malabar_regulator_table,
	.regulator_tbl_size = ARRAY_SIZE(malabar_regulator_table),
	.clk_tbl = malabar_clk_table,
	.clk_tbl_size = ARRAY_SIZE(malabar_clk_table),

	/* populate context bank */
	.context_bank_tbl = malabar_context_bank_table,
	.context_bank_tbl_size = ARRAY_SIZE(malabar_context_bank_table),

	/* platform specific resources */
	.reg_prst_tbl = malabar_reg_preset_table,
	.reg_prst_tbl_size = ARRAY_SIZE(malabar_reg_preset_table),
	.clock_source_scaling_ratio = 1,
	.fwname = "venus_v7.mbn",
	.pas_id = 9,
	.supports_mmrm = 0,

	/* caps related resorces */
	.core_data = core_data_malabar,
	.core_data_size = ARRAY_SIZE(core_data_malabar),
	.inst_cap_data = instance_cap_data_malabar,
	.inst_cap_data_size = ARRAY_SIZE(instance_cap_data_malabar),
	.inst_cap_dependency_data = instance_cap_dependency_data_malabar,
	.inst_cap_dependency_data_size = ARRAY_SIZE(instance_cap_dependency_data_malabar),
	.csc_data.vpe_csc_custom_bias_coeff = vpe_csc_custom_bias_coeff,
	.csc_data.vpe_csc_custom_matrix_coeff = vpe_csc_custom_matrix_coeff,
	.csc_data.vpe_csc_custom_limit_coeff = vpe_csc_custom_limit_coeff,
	.ubwc_config = NULL,
	.format_data = &format_data_malabar,

	/* decoder properties related*/
	.psc_avc_tbl = malabar_vdec_psc_avc,
	.psc_avc_tbl_size = ARRAY_SIZE(malabar_vdec_psc_avc),
	.psc_hevc_tbl = malabar_vdec_psc_hevc,
	.psc_hevc_tbl_size = ARRAY_SIZE(malabar_vdec_psc_hevc),
	.psc_vp9_tbl = malabar_vdec_psc_vp9,
	.psc_vp9_tbl_size = ARRAY_SIZE(malabar_vdec_psc_vp9),
	.dec_input_prop_avc = malabar_vdec_input_properties_avc,
	.dec_input_prop_hevc = malabar_vdec_input_properties_hevc,
	.dec_input_prop_vp9 = malabar_vdec_input_properties_vp9,
	.dec_input_prop_size_avc = ARRAY_SIZE(malabar_vdec_input_properties_avc),
	.dec_input_prop_size_hevc = ARRAY_SIZE(malabar_vdec_input_properties_hevc),
	.dec_input_prop_size_vp9 = ARRAY_SIZE(malabar_vdec_input_properties_vp9),
	.dec_output_prop_avc = malabar_vdec_output_properties_avc,
	.dec_output_prop_hevc = malabar_vdec_output_properties_hevc,
	.dec_output_prop_vp9 = malabar_vdec_output_properties_vp9,
	.dec_output_prop_size_avc = ARRAY_SIZE(malabar_vdec_output_properties_avc),
	.dec_output_prop_size_hevc = ARRAY_SIZE(malabar_vdec_output_properties_hevc),
	.dec_output_prop_size_vp9 = ARRAY_SIZE(malabar_vdec_output_properties_vp9),

	.msm_vidc_ssr_type = malabar_msm_vidc_ssr_type,
	.msm_vidc_ssr_type_size = ARRAY_SIZE(malabar_msm_vidc_ssr_type),
	.vpu_ver = VENUS_VERSION_AR50LT_V2,
};

int msm_vidc_get_platform_data_malabar(struct msm_vidc_core *core)
{
	d_vpr_h("%s: initialize malabar data\n", __func__);
	core->platform->data = malabar_data;
	return 0;
}

int msm_vidc_init_platform_malabar(struct msm_vidc_core *core)
{
	static struct msm_vidc_memory_ops mem_ops_ext_ar50lt;

	d_vpr_h("%s: initialize malabar ops\n", __func__);
	core->mem_ops = get_mem_ops_ext();

	memcpy(&mem_ops_ext_ar50lt, core->mem_ops, sizeof(struct msm_vidc_memory_ops));
	mem_ops_ext_ar50lt.buffer_region = msm_vidc_buffer_region_ext_ar50lt;
	core->mem_ops = &mem_ops_ext_ar50lt;

	if (!core->mem_ops) {
		d_vpr_e("%s: invalid memory ext ops\n", __func__);
		return -EINVAL;
	}
	core->res_ops = get_res_ops_ext(core);
	if (!core->res_ops) {
		d_vpr_e("%s: invalid resource ext ops\n", __func__);
		return -EINVAL;
	}

	return 0;
}
